### ISSUE TITLE
Lost Valley ledge can't be traversed to secret. 

### ISSUE THREAD

**Issue by andrewsyc** [XProger/OpenLara#123]
Can't shimmy this thin line to get the secret on top of the waterfall. 

![lost_valley_secret](https://user-images.githubusercontent.com/2940388/40685841-f38cbb9e-635a-11e8-9e4a-3e0c073ea163.png)

**Comment by andrewsyc** [comment]
While we're at it, the great pyramid also has a secret that can't be accessed the way things are currently.

![traverse_the_great_pyramid](https://user-images.githubusercontent.com/2940388/47987716-d73b1800-e0a5-11e8-887d-c79d10d78a52.png)

**Comment by vvs-** [comment]
This was fixed in OT eons ago. See description here: https://github.com/opentomb/OpenTomb/issues/86#issuecomment-120036789

**Comment by albertd1994** [comment]
> Can't shimmy this thin line to get the secret on top of the waterfall.
> 
> ![lost_valley_secret](https://user-images.githubusercontent.com/2940388/40685841-f38cbb9e-635a-11e8-9e4a-3e0c073ea163.png)

I am facing the same problem right now

**Comment by muddymind** [comment]
Just stumbled upon this issue in lost valley but found a workaround for it:

https://www.youtube.com/watch?v=2iLS7ceQNT8

**Comment by dariusSch3ll** [comment]
this is a occuring problem in 2023-09-04 so this issue is not solved, unfortunately.
